title: "selfdriven Agency"
description: "Agency in a new emerging society."
baseurl: ""
url: ""
defaults:
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: default
plugins:
  - jekyll-feed
  - jekyll-seo-tag
